// packages/convex/schema.ts
// A3 Billiards OS — Complete Convex Schema (Audited)
// Source: PRD v22.0 Final + TDD v1.3 Complete
// Audited: March 2026
//
// Two logical namespaces in one Convex deployment:
//   Central DB (11 tables):
//     users, complaints, adminNotifications, passwordResetTokens,
//     adminMfaCodes, adminAuditLog, otpRecords, sessionLogs,
//     bookingLogs, paymentReceipts, dataExportRequests
//   Club DB (9 tables):
//     clubs, tables, sessions, bookings, snacks, staffRoles,
//     cancellationCounts, customerBookingStats, sessions_archive
//
// AUDIT ROUND 1 FIXES (12 issues):
//   1.  Added cancellationReason field to sessions (PRD §6.2 forceEndSession)
//   2.  Added by_bookingId index on bookingLogs (TDD §4.4 atomic update pattern)
//   3.  Added by_customer + by_customer_club indexes on sessionLogs (PRD §8.3, §8.6)
//   4.  Added by_phone index on otpRecords (TDD §3.7 rate-limit query)
//   5.  Added by_tokenHash index on passwordResetTokens (TDD §3.5 token redemption)
//   6.  Added by_club + by_club_status indexes on sessions (financial tab, dashboard, crons)
//   7.  Added by_club index on snacks (menu load query)
//   8.  Added by_club index on staffRoles (role list query)
//   9.  Fixed bookingSettings.bookableHours validator (v.optional only, no redundant v.null())
//   10. Added by_club index on sessions_archive (monthly aggregate queries)
//   11. Added by_club index on tables (table grid loads all tables for a club)
//   12. Replaced v.any() on adminNotifications.deliveryStatus with proper map type
//
// AUDIT ROUND 2 FIXES (8 issues):
//   A.  Added notes field to bookingLogs (PRD booking detail shows customer notes from bookingLogs)
//   B.  Added currency field to sessionLogs (bill total needs currency context for multi-currency)
//   C.  Added by_global_status index on bookings (cross-club cron queries: approval deadline, no-show, reminder)
//   D.  Added by_subscriptionStatus index on clubs (subscriptionCheck cron filters by status)
//   E.  Added by_table index on sessions (best-performing tables query, table disable check)
//   F.  Added by_sessionId index on sessionLogs (session completion/credit resolve update lookup)
//   G.  Added by_reportedByClubId index on complaints (admin complaint filter by club)
//   H.  Added by_customer_status index on bookingLogs (global club limit check performance)

import { defineSchema, defineTable } from "convex/server";
import { authTables } from "@convex-dev/auth/server";
import { v } from "convex/values";

// ─────────────────────────────────────────────────────────────────────────────
// Reusable validators
// ─────────────────────────────────────────────────────────────────────────────

const userRole = v.union(
  v.literal("admin"),
  v.literal("owner"),
  v.literal("customer")
);

const sessionStatus = v.union(
  v.literal("active"),
  v.literal("completed"),
  v.literal("cancelled")
);

const paymentStatus = v.union(
  v.literal("pending"),
  v.literal("paid"),
  v.literal("credit")
);

const paymentMethod = v.union(
  v.literal("cash"),
  v.literal("upi"),
  v.literal("card"),
  v.literal("credit")
);

// creditResolvedMethod excludes 'credit' — you resolve FROM credit TO a real method
const creditResolveMethod = v.union(
  v.literal("cash"),
  v.literal("upi"),
  v.literal("card")
);

const bookingStatus = v.union(
  v.literal("pending_approval"),
  v.literal("confirmed"),
  v.literal("rejected"),
  v.literal("cancelled_by_customer"),
  v.literal("cancelled_by_club"),
  v.literal("expired"),
  v.literal("completed")
);

const subscriptionStatus = v.union(
  v.literal("active"),
  v.literal("grace"),
  v.literal("frozen")
);

const complaintType = v.union(
  v.literal("violent_behaviour"),
  v.literal("theft"),
  v.literal("runaway_without_payment"),
  v.literal("late_credit_payment")
);

const notificationTargetType = v.union(
  v.literal("all"),
  v.literal("selected"),
  v.literal("role")
);

const resetTokenType = v.union(
  v.literal("accountPassword"),
  v.literal("settingsPasscode")
);

const adminAuditAction = v.union(
  v.literal("phone_update"),
  v.literal("admin_profile_edit"),
  v.literal("user_freeze"),
  v.literal("user_unfreeze"),
  v.literal("password_reset"),
  v.literal("passcode_reset"),
  v.literal("role_change"),
  v.literal("complaint_dismiss"),
  v.literal("session_force_end")
);

// Per-recipient delivery status for admin broadcasts
const deliveryStatusValue = v.union(
  v.literal("sent"),
  v.literal("delivered"),
  v.literal("failed")
);

const snackOrder = v.object({
  snackId: v.id("snacks"),
  name: v.string(),
  qty: v.number(),
  priceAtOrder: v.number(),
});

const specialRate = v.object({
  id: v.string(),                    // UUID generated by frontend (crypto.randomUUID())
  ratePerMin: v.number(),
  startTime: v.string(),             // HH:MM
  endTime: v.string(),               // HH:MM — midnight-crossing supported (endTime < startTime)
  daysOfWeek: v.array(v.number()),   // 0=Sun, 6=Sat
  label: v.string(),
});

const locationObj = v.object({
  lat: v.number(),
  lng: v.number(),
});

const operatingHoursObj = v.object({
  open: v.string(),                  // HH:MM
  close: v.string(),                 // HH:MM
  daysOfWeek: v.array(v.number()),   // 0=Sun, 6=Sat
});

const bookableHoursObj = v.object({
  open: v.string(),                  // HH:MM — must fall within operatingHours (validated server-side)
  close: v.string(),                 // HH:MM — must fall within operatingHours (validated server-side)
  daysOfWeek: v.array(v.number()),   // 0=Sun, 6=Sat
});

// FIX #9: Simplified from v.optional(v.union(bookableHoursObj, v.null())) — v.optional handles absence
const bookingSettingsObj = v.object({
  enabled: v.boolean(),                           // Default: false
  maxAdvanceDays: v.number(),                      // Default: 7
  minAdvanceMinutes: v.number(),                   // Default: 60
  slotDurationOptions: v.array(v.number()),        // Default: [30, 60, 90, 120]
  cancellationWindowMin: v.number(),               // Default: 30
  approvalDeadlineMin: v.number(),                 // Default: 60
  bookableTableTypes: v.array(v.string()),         // Default: [] — owner must select ≥1 before enabling
  bookableHours: v.optional(bookableHoursObj),     // Default: undefined — must be configured before enabling
});

// ─────────────────────────────────────────────────────────────────────────────
// CENTRAL DATABASE TABLES (11 tables)
// ─────────────────────────────────────────────────────────────────────────────

export default defineSchema({
  ...authTables,

  // ── users ──────────────────────────────────────────────────────────────────
  // Replaces authTables.users — A3-extended profile + roles (Convex Auth compatible).
  // All roles (admin, owner, customer) share one table.
  // Field relevance varies by role:
  //   - settingsPasscodeHash/Set: owner only
  //   - phone: mandatory for customers, contact ref for owners, absent for admins
  //   - phoneVerified: gates customer accounts only
  // RLS: any authenticated user can read; only admin or self can modify.
  // Default values at creation: isFrozen=false, settingsPasscodeSet=false,
  //   complaints=[], fcmTokens=[], consentGiven=true, consentGivenAt=Date.now()
  users: defineTable({
    phone: v.optional(v.string()),               // Unique. Mandatory for customers (WhatsApp OTP verified).
                                                  // Populated for owners at onboarding (contact ref only).
                                                  // Null/absent for admin accounts.
    phoneVerified: v.boolean(),                   // Must be true before a customer account is active.
                                                  // Gates booking submission and session start from booking.
    name: v.string(),                             // 2–100 chars. Leading/trailing whitespace stripped server-side.
                                                  // Same validation on self-registration, staff-creation, profile edits.
    age: v.number(),                              // Age at registration. Minimum: 18. Not updated afterward.
    email: v.optional(v.string()),                // Required for email/password login or Google Sign-In.
                                                  // Editing also updates the Convex Auth identity.
    googleId: v.optional(v.string()),             // Google OAuth subject ID. Set on Google Sign-In.
                                                  // Used for primary lookup in verifyGoogleToken flow.
    fcmTokens: v.array(v.string()),               // FCM device tokens — one per active device/session.
                                                  // Stale tokens auto-removed on Firebase invalid response.
                                                  // Deduped server-side on login.
    settingsPasscodeHash: v.optional(v.string()), // bcrypt hash (10 rounds) of 6-digit settings PIN.
                                                  // Owner only. Null until first setup.
    settingsPasscodeSet: v.boolean(),             // False until first-login passcode setup completed.
                                                  // Clearing this (via email reset) forces re-setup on next login.
    complaints: v.array(v.id("complaints")),       // Live array of active complaint IDs — source of truth.
                                                  // Non-empty triggers banner alert on customer login.
                                                  // Checked at session start (advisory only).
    isFrozen: v.boolean(),                        // Blocks all panel logins at Convex auth layer.
                                                  // Set exclusively by admin action — subscription expiry
                                                  // never modifies this (uses clubs.subscriptionStatus instead).
    role: userRole,                               // Determines panel access. Set at creation.
                                                  // Valid transitions: owner → admin only (via admin promote).
    deletionRequestedAt: v.optional(v.number()),  // Unix ms. Triggers 30-day grace period.
                                                  // Checked by: booking submission, session start, data export.
                                                  // Login blocked immediately when set.
    ownerDataExportRequestedAt: v.optional(v.number()), // Unix ms. Rate-limits owner data export requests (24h).
    /** Set when admin completes email MFA; cleared when a new MFA code is issued (login flow). */
    adminMfaVerifiedAt: v.optional(v.number()),
    deletionCancelToken: v.optional(v.string()),  // SHA-256 hashed token for email cancellation link. Single-use.
    consentGiven: v.boolean(),                    // Explicit Privacy Policy/ToS consent checkbox.
                                                  // Required true before account creation (server-enforced).
                                                  // Always true for legacy accounts bootstrapped before this field.
    consentGivenAt: v.optional(v.number()),       // Unix ms when consent was given. Null for pre-consent accounts.
    createdAt: v.number(),                        // Unix ms.
  })
    .index("by_phone", ["phone"])                 // Phone duplicate detection, OTP flow, customer lookup
    .index("by_email", ["email"])                 // Google Sign-In email fallback, email/password lookup
    .index("by_googleId", ["googleId"]),          // Google Sign-In primary lookup

  // ── complaints ─────────────────────────────────────────────────────────────
  // Cross-club customer flags. Central DB. Filed by owners, visible to all clubs.
  // Cannot be filed against anonymous guest sessions (no central identity).
  // On removal: sets removedAt + removedById, pulls ID from users.complaints[].
  // Customer deletion: complaint records retained 90 days for affected clubs to act.
  // RLS: any authenticated user can read; admin or unflagged (removedById undefined) can modify.
  complaints: defineTable({
    userId: v.id("users"),                        // The reported customer.
    reportedByClubId: v.id("clubs"),              // Club that filed the complaint.
    sessionId: v.optional(v.id("sessions")),      // Optional reference to the incident session.
    type: complaintType,                          // violent_behaviour | theft | runaway_without_payment | late_credit_payment
    description: v.string(),                      // Free-text detail notes.
    removedAt: v.optional(v.number()),            // Unix ms. Soft-delete timestamp.
    removedById: v.optional(v.id("users")),       // Admin or owner who removed the complaint.
    dismissalReason: v.optional(v.string()),       // Max 500 chars. Required for admin dismiss; optional for owner retraction.
    createdAt: v.number(),                        // Unix ms.
  })
    .index("by_userId", ["userId"])                // Admin complaint management filters by customer
    // FIX G: Admin complaint view filters by club (PRD §6.3); owner views own club's complaints
    .index("by_reportedByClubId", ["reportedByClubId"]),

  // ── adminNotifications ─────────────────────────────────────────────────────
  // Admin broadcast push notifications with per-recipient delivery tracking.
  // Rate-limited: max 10 broadcasts per hour per admin (fixed hour boundary).
  // Frozen accounts (isFrozen=true) excluded from 'all' and 'role' targets.
  // FIX #12: deliveryStatus uses v.map instead of v.any() for type safety.
  adminNotifications: defineTable({
    sentByAdminId: v.id("users"),                 // Admin who composed the broadcast.
    title: v.string(),                            // Push notification title.
    body: v.string(),                             // Push notification body.
    targetType: notificationTargetType,           // 'all' | 'selected' | 'role'
    targetUserIds: v.optional(v.array(v.id("users"))), // Populated when targetType === 'selected'.
    targetRole: v.optional(v.union(               // Populated when targetType === 'role'.
      v.literal("owner"),
      v.literal("customer")
    )),
    deliveryStatus: v.record(v.string(), deliveryStatusValue), // Map<userId, 'sent'|'delivered'|'failed'>
    createdAt: v.number(),                        // Unix ms.
  })
    .index("by_createdAt", ["createdAt"])
    .index("by_sentByAdmin_createdAt", ["sentByAdminId", "createdAt"]),

  // ── passwordResetTokens ────────────────────────────────────────────────────
  // SHA-256 hashed tokens for password and passcode resets.
  // Generated as 32-byte hex via crypto.randomBytes in Convex action.
  // 1-hour expiry. Single-use — marked used immediately on redemption.
  // Reset links open a page on the A3 Billiards OS web domain (not deep links).
  passwordResetTokens: defineTable({
    userId: v.id("users"),                        // Account the token belongs to.
    tokenHash: v.string(),                        // SHA-256 hash of the raw 32-byte hex token.
    type: resetTokenType,                         // 'accountPassword' | 'settingsPasscode'
    expiresAt: v.number(),                        // Unix ms — 1 hour from creation.
    used: v.boolean(),                            // Marked true on redemption; reuse rejected.
    createdAt: v.number(),                        // Unix ms.
  })
    // FIX #5: verifyAndConsumeToken looks up by tokenHash — needs index
    .index("by_tokenHash", ["tokenHash"])
    // Rate limit: count recent password reset requests per user
    .index("by_userId", ["userId"]),

  // ── passwordResetContinuations ─────────────────────────────────────────────
  // Issued when the email link token is verified (single-use). Short TTL before set-password.
  passwordResetContinuations: defineTable({
    userId: v.id("users"),
    tokenHash: v.string(),                        // SHA-256 of completion UUID (raw shown once to client).
    expiresAt: v.number(),                        // Unix ms — 15 minutes from creation.
    createdAt: v.number(),
  }).index("by_tokenHash", ["tokenHash"]),

  // ── adminMfaCodes ──────────────────────────────────────────────────────────
  // SHA-256 hashed 6-digit MFA codes for admin login. 10-minute expiry.
  // Requesting a new code invalidates all existing unused codes for that admin.
  adminMfaCodes: defineTable({
    adminId: v.id("users"),                       // Admin user the code was issued to.
    emailNormalized: v.optional(v.string()),     // Lowercase email — sliding-window rate limit (5/hr per email).
    codeHash: v.string(),                         // bcrypt hash of the 6-digit code (stored by MFA action).
    expiresAt: v.number(),                        // Unix ms — 10 minutes from creation.
    used: v.boolean(),                            // Marked true on successful verification.
    createdAt: v.number(),                        // Unix ms.
  })
    .index("by_admin", ["adminId"])              // storeMfaCode + checkMfaCode lookup
    .index("by_email_normalized_createdAt", ["emailNormalized", "createdAt"]),

  // ── adminAuditLog ──────────────────────────────────────────────────────────
  // Immutable audit trail for sensitive admin actions. DPDP Act 2023 compliance.
  // Actions: phone_update, admin_profile_edit, user_freeze, user_unfreeze, password_reset,
  //          passcode_reset, role_change, complaint_dismiss, session_force_end
  adminAuditLog: defineTable({
    adminId: v.id("users"),                       // Admin who performed the action.
    action: adminAuditAction,                     // Action type enum.
    targetUserId: v.optional(v.id("users")),      // User the action was performed on.
    previousValue: v.optional(v.string()),         // Previous value (e.g. old phone number). String for flexibility.
    newValue: v.optional(v.string()),              // New value (e.g. new phone number).
    notes: v.optional(v.string()),                 // Optional context or reason (e.g. force-end reason, max 300 chars).
    createdAt: v.number(),                        // Unix ms.
  })
    .index("by_admin", ["adminId"]),              // Audit log filtering by admin
    // Intentionally no by_targetUserId — admin dashboard filters by admin, not target

  // ── otpRecords ─────────────────────────────────────────────────────────────
  // WhatsApp OTP verification records. bcrypt-hashed codes (10 rounds, in action).
  // 10-minute expiry. Max 3 incorrect attempts → 5-minute cooldown.
  // Rate-limited: max 5 dispatches per phone per rolling 60-minute window (see otp.countRecentDispatches).
  otpRecords: defineTable({
    phone: v.string(),                            // Phone number the OTP was sent to (E.164 format).
    otpHash: v.string(),                          // bcrypt hash of the 6-digit code.
    attempts: v.number(),                         // Incorrect attempt counter. Blocked after 3.
    cooldownUntil: v.optional(v.number()),        // Unix ms — set to now + 5 min after 3 failed attempts.
    expiresAt: v.number(),                        // Unix ms — 10 minutes from creation.
    used: v.boolean(),                            // Marked true on successful verification.
    createdAt: v.number(),                        // Unix ms.
  })
    // FIX #4: Rate-limit check queries by phone to count dispatches in the last hour
    .index("by_phone", ["phone"]),

  // ── sessionLogs ────────────────────────────────────────────────────────────
  // Lightweight cross-club session references. Central DB.
  // Powers customer session history across all clubs without exposing club billing data.
  // Written atomically in the same Convex mutation that creates/updates the club DB session.
  // On session completion or credit resolution, updated in the same transaction.
  // Guest sessions (isGuest: true) are NEVER written to sessionLogs — no central identity.
  sessionLogs: defineTable({
    sessionId: v.id("sessions"),                  // Reference to full session record in club DB.
    customerId: v.id("users"),                    // Verified customer. Non-nullable (guest sessions excluded).
    clubId: v.id("clubs"),                        // Which club.
    clubName: v.string(),                         // Denormalised at session creation time.
    tableLabel: v.string(),                       // Denormalised table label.
    startTime: v.number(),                        // Unix ms.
    endTime: v.optional(v.number()),              // Unix ms. Null while active.
    billTotal: v.optional(v.number()),            // Copied from club DB on session completion.
    currency: v.optional(v.string()),              // FIX B: ISO 4217 denormalised at session creation. Needed for multi-currency display.
                                                  // Optional for backward compatibility with pre-existing records.
    paymentStatus: paymentStatus,                 // 'pending' | 'paid' | 'credit'
    paymentMethod: v.optional(paymentMethod),     // 'cash' | 'upi' | 'card' | 'credit'
    /** Mirrored from club `sessions` when credit is resolved (list badge: Credit Resolved). */
    creditResolvedAt: v.optional(v.number()),
    creditResolvedMethod: v.optional(
      v.union(v.literal("cash"), v.literal("upi"), v.literal("card")),
    ),
    status: sessionStatus,                        // 'active' | 'completed' | 'cancelled'
    createdAt: v.number(),                        // Unix ms when sessionLog entry was created.
    updatedAt: v.number(),                        // Unix ms of last status change (completion, credit resolve).
  })
    // FIX #3: Customer session history (PRD §8.6) queries by customerId across all clubs
    .index("by_customer", ["customerId"])
    // FIX #3: "You've played here 5 times" (PRD §8.3) queries by customerId + clubId
    .index("by_customer_club", ["customerId", "clubId"])
    // FIX F: Session completion and credit resolve mutations find sessionLog by sessionId
    .index("by_sessionId", ["sessionId"])
    // Admin dashboard: cross-club active session count
    .index("by_status", ["status"])
    // Admin dashboard: paid revenue aggregates (completed + paid)
    .index("by_status_payment", ["status", "paymentStatus"]),

  // ── bookingLogs ────────────────────────────────────────────────────────────
  // Lightweight cross-club booking references. Central DB.
  // Powers customer "My Bookings" screen across all clubs.
  // Written atomically in the same Convex mutation that creates/updates the club DB booking.
  // Updated whenever booking status changes.
  // When club is deleted/purged, bookingLogs entries are retained (clubId becomes stale)
  //   but denormalised fields (clubName, clubAddress, thumbnailPhotoId) remain readable.
  bookingLogs: defineTable({
    bookingId: v.id("bookings"),                  // Reference to full booking record in club DB.
    customerId: v.id("users"),                    // Customer who submitted the booking.
    clubId: v.id("clubs"),                        // Which club.
    clubName: v.string(),                         // Denormalised at booking creation time. Retained after club rename.
    clubAddress: v.optional(v.string()),           // Denormalised at submission. Fallback when getClubProfile returns null.
    thumbnailPhotoId: v.optional(v.string()),      // Convex file storage ID of first club photo at submission. Fallback thumbnail.
    tableType: v.string(),                        // Denormalised requested table type for display without cross-DB lookup.
    status: bookingStatus,                        // Mirrored from club DB booking on every status change.
    rejectionReason: v.optional(v.string()),       // Mirrored on rejection. Customer sees reason without cross-DB lookup.
    confirmedTableLabel: v.optional(v.string()),   // Denormalised table label. Set when status transitions to 'confirmed'.
    estimatedCost: v.optional(v.number()),         // ratePerMin × duration at submission time. Not updated if rates change.
    currency: v.string(),                         // ISO 4217 locked at booking submission from clubs.currency.
    notes: v.optional(v.string()),                 // FIX A: Customer-provided notes denormalised at submission. Max 200 chars.
                                                  // Required for booking detail screen (PRD §8.5) when club is deleted/purged.
    requestedDate: v.string(),                    // YYYY-MM-DD in club timezone.
    requestedStartTime: v.string(),               // HH:MM in club timezone.
    requestedDurationMin: v.number(),             // Requested duration in minutes.
    createdAt: v.number(),                        // Unix ms.
    updatedAt: v.number(),                        // Unix ms.
  })
    // My Bookings screen + global booking club limit (distinct active clubIds check in submitBooking)
    .index("by_customer", ["customerId"])
    // FIX H: Global club limit check (submitBooking) filters by customerId + status for active bookings
    .index("by_customer_status", ["customerId", "status"])
    // FIX #2: startSessionFromBooking + every status-change mutation looks up bookingLog by bookingId
    .index("by_bookingId", ["bookingId"]),

  // ── paymentReceipts ────────────────────────────────────────────────────────
  // Razorpay webhook idempotency table. Central DB.
  // Before updating subscriptionExpiresAt, the webhook handler checks for the payment_id.
  // If payment_id exists → return 200 immediately (already processed).
  // If not → write receipt, then update subscriptionExpiresAt.
  // Guarantees exactly-once processing even if Razorpay fires the webhook multiple times.
  paymentReceipts: defineTable({
    paymentId: v.string(),                        // Razorpay payment_id. Unique (enforced via index check).
    ownerId: v.id("users"),                       // Owner whose subscription was renewed.
    clubId: v.id("clubs"),                        // Club whose subscription was renewed.
    amountPaid: v.number(),                       // Amount in Razorpay processing currency (INR). Informational/audit only.
    processedAt: v.number(),                      // Unix ms when webhook was first successfully processed.
  })
    .index("by_paymentId", ["paymentId"])          // Idempotency check: does this payment_id already exist?
    .index("by_owner", ["ownerId"]),               // Club lookup: find club record for this owner

  // ── dataExportRequests ─────────────────────────────────────────────────────
  // Customer data export (GDPR-style). Rate-limited 1 request / 24h per user (sliding window).
  dataExportRequests: defineTable({
    userId: v.id("users"),
    requestedAt: v.number(),
  })
    .index("by_userId", ["userId"]),

  // ─────────────────────────────────────────────────────────────────────────────
  // PER-CLUB DATABASE TABLES (9 tables)
  // ─────────────────────────────────────────────────────────────────────────────

  // ── clubs ──────────────────────────────────────────────────────────────────
  // One record per club. Created atomically with payment on Onboarding Website.
  // Contains all club-level settings: rates, booking config, profile, subscription.
  // subscriptionStatus lifecycle: active → grace (at expiry) → frozen (24h later).
  // Renewal formula: newExpiresAt = max(currentSubscriptionExpiresAt, now) + purchasedPeriod.
  //   - Early renewal from active: preserves unused time.
  //   - Grace/frozen renewal: max() = now (expiresAt is past).
  // Subscription freeze enforced at Convex auth layer — blocks all Owner App API calls.
  // Active sessions paused in UI during freeze; on renewal, resume from original startTime.
  clubs: defineTable({
    ownerId: v.id("users"),                       // The owner user. One club per owner account.
    name: v.string(),                             // Club display name.
    address: v.string(),                          // Club address as entered during onboarding.
    subscriptionStatus: subscriptionStatus,        // 'active' | 'grace' | 'frozen'
    subscriptionExpiresAt: v.number(),            // Unix ms. Checked daily by subscriptionCheck cron.
    baseRatePerMin: v.number(),                   // Must be > 0 (validated server-side on onboarding + settings).
    currency: v.string(),                         // ISO 4217 currency code. Applies to all new sessions.
                                                  // Historical sessions retain sessions.currency as locked at start.
    minBillMinutes: v.number(),                   // Must be >= 1 (validated server-side).
    timezone: v.string(),                         // IANA timezone identifier (e.g. 'Asia/Kolkata').
                                                  // Used for: bookable hours, cancellation day reset, date attribution.
    createdAt: v.number(),                        // Unix ms.
    specialRates: v.array(specialRate),           // Time-based rate overrides. Backend rejects overlapping rules.
                                                  // Midnight-crossing supported (endTime < startTime → split into two windows).
                                                  // Each has UUID id for targeted edits/deletes.
    isDiscoverable: v.boolean(),                  // Controls customer search visibility. Default: false.
                                                  // Club appears in results when true, regardless of bookingSettings.enabled.
                                                  // Only clubs with subscriptionStatus 'active' or 'grace' shown.
    location: v.optional(locationObj),            // Geocoded lat/lng from club address. Set during onboarding.
                                                  // Adjustable via pin drag in Settings. Used for Haversine distance calc.
                                                  // If missing, club doesn't appear in location-based search (name search only).
    description: v.optional(v.string()),           // Short club bio/tagline. Max 500 chars.
    photos: v.optional(v.array(v.string())),       // Convex file storage IDs. Maximum 5. Max 5MB per image. JPEG/PNG/WebP.
    amenities: v.optional(v.array(v.string())),    // Predefined (AC, Parking, Cafe, WiFi, Lounge, Restrooms) + custom entries.
    operatingHours: v.optional(operatingHoursObj), // Displayed on club profile. Required before enabling booking.
    bookingSettings: bookingSettingsObj,           // Online booking configuration. All defaults must be set at creation.
                                                  // Enable requires: ≥1 bookableTableType, bookableHours configured,
                                                  // operatingHours configured, ≥1 active table matching a bookable type.
  })
    .index("by_owner", ["ownerId"])                // Webhook → club lookup, renewal, owner-scoped queries
    // FIX D: subscriptionCheck cron queries clubs by status to find expiring/grace subscriptions
    .index("by_subscriptionStatus", ["subscriptionStatus"]),

  // ── tables ─────────────────────────────────────────────────────────────────
  // Physical billiards tables. Soft delete via isActive (preserves session history).
  // Table with active session cannot be disabled until session is ended/cancelled.
  // Table lock mechanism: tableLock + tableLockExpiry for concurrent booking prevention.
  //   Standard lock: now + 30s. OTP flow: now + 3 minutes.
  //   Lock cleanup via ctx.scheduler (not crons). Token matching prevents stale cleanup.
  // tableType stored normalised to lowercase at write time by both tables mutation
  //   and bookingSettings mutation. Ensures case-insensitive matching. UI shows capitalised.
  tables: defineTable({
    clubId: v.id("clubs"),                        // Parent club.
    label: v.string(),                            // e.g. 'Table 1', 'VIP Table'.
    isActive: v.boolean(),                        // Soft delete. Preserves session history.
    currentSessionId: v.optional(v.id("sessions")), // Non-null when occupied.
                                                  // Cleared to null in same mutation that marks session completed/cancelled.
    tableLock: v.optional(v.string()),             // Lock token (UUID) written when booking modal opens.
    tableLockExpiry: v.optional(v.number()),       // Unix ms expiry. Concurrent attempts check this.
    tableType: v.optional(v.string()),             // Free-text. Stored lowercase. e.g. 'french', 'snooker', '8-ball'.
    floor: v.optional(v.string()),                 // Floor label (e.g. 'Ground Floor', 'Level 2').
  })
    // FIX #11: Table grid loads all tables for a club (Slots tab, table management)
    .index("by_club", ["clubId"])
    // Availability engine: getAvailableSlots filters by clubId + tableType
    .index("by_club_type", ["clubId", "tableType"]),

  // ── sessions ───────────────────────────────────────────────────────────────
  // A single table usage from start to checkout/billing.
  // Lifecycle: active → completed (checkout) or cancelled (staff cancel / admin force-end).
  // Sessions are NEVER auto-completed. Left running indefinitely if staff forgets.
  // Rate and minBillMinutes locked at session start — mid-session club changes ignored.
  // Billing formula:
  //   actualMinutes = ceil((endTime - startTime) / 60000)
  //   billableMinutes = max(actualMinutes, session.minBillMinutes)
  //   tableSubtotal = billableMinutes × session.ratePerMin
  //   discountedTable = tableSubtotal × (1 − discount% / 100)
  //   snackTotal = Σ(snackPrice × qty) — never discounted
  //   FINAL_BILL = discountedTable + snackTotal
  // Guest sessions (isGuest: true) have no customerId and are never in sessionLogs.
  sessions: defineTable({
    tableId: v.id("tables"),                      // Which table.
    clubId: v.id("clubs"),                        // Parent club.
    customerId: v.optional(v.id("users")),        // Null for anonymous guest sessions.
    guestName: v.optional(v.string()),             // Name for anonymous guests. Null for verified customers.
    guestAge: v.optional(v.number()),              // Age for anonymous guests. Null for verified customers.
    isGuest: v.boolean(),                         // True for OTP fallback anonymous flow.
    startTime: v.number(),                        // Unix ms. Timer runs server-side from this.
    endTime: v.optional(v.number()),              // Unix ms. Null while active.
    billableMinutes: v.optional(v.number()),       // Null while active; set at checkout.
    ratePerMin: v.number(),                       // Rate locked at session start.
                                                  // Selection: if startTime falls within any specialRate window
                                                  // (matching time-of-day and day-of-week), that specialRate.ratePerMin;
                                                  // otherwise club baseRatePerMin. Mid-session changes ignored.
    minBillMinutes: v.number(),                   // Locked at session start from club.minBillMinutes.
                                                  // Checkout uses this locked value, not current club setting.
    currency: v.string(),                         // ISO 4217 locked at session start.
    snackOrders: v.array(snackOrder),             // Items added during session. Each: { snackId, name, qty, priceAtOrder }
                                                  // Cannot add after paid. Credit sessions editable until resolved.
    billTotal: v.optional(v.number()),            // Final computed total. Null while active.
    discount: v.optional(v.number()),             // 0–100. Null = no discount. Applies to table subtotal only, never snacks.
    paymentMethod: v.optional(paymentMethod),     // 'cash' | 'upi' | 'card' | 'credit'. Set at checkout.
    paymentStatus: paymentStatus,                 // 'pending' at creation; 'paid' or 'credit' at checkout.
    status: sessionStatus,                        // 'active' | 'completed' | 'cancelled'
    // FIX #1: forceEndSession (PRD §6.2) sets cancellationReason to 'admin_force_end'
    cancellationReason: v.optional(v.string()),    // Reason for cancellation. 'admin_force_end' for force-ended sessions.
                                                  // Null for normal cancellations by staff. Max 300 chars for admin force-end.
    timerAlertMinutes: v.optional(v.number()),    // FCM alert fires when elapsed ≥ this value. Updatable mid-session.
    timerAlertFiredAt: v.optional(v.number()),    // Unix ms. Prevents duplicate alerts on app restart.
                                                  // Updating timerAlertMinutes resets this (clears it) so alert can refire.
    creditResolvedAt: v.optional(v.number()),     // Unix ms when credit is resolved (Mark as Paid action).
    creditResolvedMethod: v.optional(creditResolveMethod), // 'cash' | 'upi' | 'card'. Excludes 'credit'.
    staffAcknowledgedComplaint: v.optional(v.boolean()), // True when staff tapped 'Acknowledge and proceed'.
    acknowledgedByRoleId: v.optional(v.id("staffRoles")), // Active role at acknowledgement. Null if owner mode.
    acknowledgedAt: v.optional(v.number()),        // Unix ms when complaint was acknowledged.
    bookingId: v.optional(v.id("bookings")),      // Reference to originating booking. Null for walk-in sessions.
    discountAppliedByRoleId: v.optional(v.id("staffRoles")), // Role that applied discount. Null if owner mode.
    discountAppliedAt: v.optional(v.number()),    // Unix ms when discount was applied. Null if no discount.
    createdAt: v.number(),                        // Unix ms when session was created (timer started).
    updatedAt: v.number(),                        // Unix ms of last change (snack added, completed, credit resolved).
  })
    // FIX #6: Financial tab, Home Page daily revenue, admin dashboard — all query by club
    .index("by_club", ["clubId"])
    // FIX #6: Financial tab filters by club + status. Cron queries active sessions.
    //         Outstanding credits: club + paymentStatus. Home: club + status + endTime date range.
    .index("by_club_status", ["clubId", "status"])
    // FIX E: Best-performing tables query (PRD §7.6) + table disable check (active session exists?)
    .index("by_table", ["tableId"])
    // Owner complaints: link session picker (completed sessions for customer at club)
    .index("by_club_customer", ["clubId", "customerId"]),

  // ── bookings ───────────────────────────────────────────────────────────────
  // Online booking records. Per-club DB.
  // 7-state lifecycle with strict transition validation (BOOKING_006 on invalid):
  //   pending_approval → confirmed | rejected | cancelled_by_customer | expired
  //   confirmed → cancelled_by_customer | cancelled_by_club | completed | expired
  // submitBooking performs 11 fail-fast validation checks inside the mutation.
  // Availability engine: getAvailableSlots reactive query, 30-min increments, zero gap.
  // Pending bookings treated as blocking (conservative for v1).
  // startSessionFromBooking window: hardcoded 15 min before to 30 min after.
  bookings: defineTable({
    clubId: v.id("clubs"),                        // Parent club.
    customerId: v.id("users"),                    // Customer who submitted the booking.
    tableType: v.string(),                        // Requested table type (e.g. 'Snooker', '8-ball').
    requestedDate: v.string(),                    // YYYY-MM-DD in club timezone.
    requestedStartTime: v.string(),               // HH:MM in club timezone.
    requestedDurationMin: v.number(),             // Requested duration in minutes. Must be in slotDurationOptions.
    status: bookingStatus,                        // 7-state enum. Every mutation verifies current status first.
    rejectionReason: v.optional(v.string()),       // Max 300 chars. Owner-provided on rejection.
    notes: v.optional(v.string()),                 // Max 200 chars. Customer-provided notes (e.g. 'birthday party').
    estimatedCost: v.optional(v.number()),         // Server-computed: max(duration, minBillMinutes) × applicableRate.
                                                  // Never trusted from client. Not updated if rates change after submission.
    currency: v.string(),                         // ISO 4217 locked at submission from clubs.currency.
    confirmedTableId: v.optional(v.id("tables")), // Table assigned by owner during approval. May differ from initial.
                                                  // If null at arrival, staff picks a table of matching type.
    approvedAt: v.optional(v.number()),           // Unix ms when approved.
    approvedByRoleId: v.optional(v.id("staffRoles")), // Staff role that approved. Null if owner unrestricted mode.
                                                  // Server enforces allowedTableIds if role has restrictions.
    approvedByRoleName: v.optional(v.string()),    // Denormalised role name at approval time (e.g. 'Manager').
                                                  // Survives role deletion for audit trail readability.
    sessionId: v.optional(v.id("sessions")),      // Linked when converted to session via startSessionFromBooking.
    reminderSentAt: v.optional(v.number()),       // Unix ms. Prevents duplicate 1-hour-before reminder sends.
    approvalReminderSentAt: v.optional(v.number()), // Unix ms. Prevents duplicate 50%-deadline owner reminder sends.
    createdAt: v.number(),                        // Unix ms.
    updatedAt: v.number(),                        // Unix ms.
  })
    // Availability engine: all bookings for a club on a given date
    .index("by_club_date", ["clubId", "requestedDate"])
    // Max active bookings check (2 per customer per club)
    .index("by_customer", ["customerId"])
    // Owner's Pending/Upcoming sections + approval deadline cron + no-show cron
    .index("by_status", ["clubId", "status"])
    // FIX C: Cross-club crons (approvalDeadline, noShowDetection, bookingReminder) query all bookings by status
    .index("by_global_status", ["status"]),

  // ── cancellationCounts ─────────────────────────────────────────────────────
  // Per customer per club per day cancellation tracking.
  // Max 3 cancellations per day. Resets at midnight in club timezone.
  // Only customer-initiated cancellations increment this.
  // System-triggered cancellations (account deletion auto-cancel) do NOT increment.
  // Club-side cancellations and system expirations do NOT count against customer.
  cancellationCounts: defineTable({
    customerId: v.id("users"),                    // Customer whose cancellations are tracked.
    clubId: v.id("clubs"),                        // Club where cancellations are tracked.
    date: v.string(),                             // YYYY-MM-DD in club timezone. Reset at midnight club local time.
    count: v.number(),                            // Number of cancellations on this date. Max enforced: 3.
  })
    .index("by_customer_club_date", ["customerId", "clubId", "date"]),

  // ── customerBookingStats ───────────────────────────────────────────────────
  // Per customer per club booking reliability metrics.
  // Visible to owner during booking approval review.
  // Owner sees both this-club stats AND platform-wide aggregate (cross-club query on bookingLogs).
  customerBookingStats: defineTable({
    customerId: v.id("users"),                    // Customer.
    clubId: v.id("clubs"),                        // Club.
    noShowCount: v.number(),                      // Incremented when confirmed booking expires (30 min past start, no session).
    lateCancellationCount: v.number(),            // Incremented on late cancel (within cancellationWindowMin of start).
                                                  // No blocking effect in Phase 1. Used for Phase 2 penalty enforcement.
    totalBookings: v.number(),                    // Total bookings submitted at this club (all statuses).
  })
    .index("by_customer_club", ["customerId", "clubId"]),

  // ── snacks ─────────────────────────────────────────────────────────────────
  // Club menu items. Two-level visibility:
  //   isAvailable=false: temporarily unavailable (toggle without deleting).
  //   isDeleted=true: permanently removed from menu (soft delete, record retained for history).
  // Snack cutoff rules:
  //   Cannot add to cancelled session.
  //   Cannot add after completed session is marked paid.
  //   Credit sessions remain editable until credit is resolved.
  snacks: defineTable({
    clubId: v.id("clubs"),                        // Parent club.
    name: v.string(),                             // Item name.
    price: v.number(),                            // Price per unit in club's current currency.
    isAvailable: v.boolean(),                     // Toggle without deleting. False = temporarily unavailable.
    isDeleted: v.boolean(),                       // Soft delete. True = permanently removed from menu.
                                                  // Record retained so historical snackOrders[] references remain valid.
  })
    // FIX #7: Every snack menu load queries all snacks for a club
    .index("by_club", ["clubId"]),

  // ── staffRoles ─────────────────────────────────────────────────────────────
  // Named roles for staff operating the owner's shared device.
  // Staff don't have individual logins — owner selects active role via 6-digit passcode.
  // Active role stored client-side; mutations accept roleId and validate server-side.
  // Deleting an active role: app detects stale roleId, reverts to unrestricted owner mode.
  staffRoles: defineTable({
    clubId: v.id("clubs"),                        // Parent club.
    name: v.string(),                             // e.g. 'Cashier', 'Manager', 'Supervisor'.
    allowedTabs: v.array(v.string()),             // Valid: 'slots' | 'snacks' | 'financials' | 'complaints' | 'bookings'.
                                                  // Must have at least one. Empty array rejected with STAFF_001.
    allowedTableIds: v.optional(v.array(v.id("tables"))), // Null = access to all tables.
                                                  // Server enforces: approval/session start rejects if table outside set.
    canFileComplaints: v.boolean(),               // Whether this role can file complaints against customers.
    canApplyDiscount: v.boolean(),                // Whether this role can apply discount at checkout. Default: true.
    maxDiscountPercent: v.optional(v.number()),    // 0–100. Default: 10. Null = no cap.
                                                  // Checkout mutation enforces server-side. Rejects above cap.
                                                  // Owner in unrestricted mode has no cap (field irrelevant).
  })
    // FIX #8: Role list loads all roles for a club (Settings > Staff Roles)
    .index("by_club", ["clubId"]),

  // ── sessions_archive ───────────────────────────────────────────────────────
  // Sessions older than 2 years are moved here by daily cron (runs at 04:00 UTC).
  // Cron handler checks day-of-month === 1 inside handler (no .monthly() in Convex API).
  // NO reactive queries — read-only historical cold storage.
  // Monthly financial aggregates are pre-computed at month-end to avoid full-table scans.
  // Schema mirrors sessions exactly for seamless data migration.
  sessions_archive: defineTable({
    /** Original `sessions._id` before archival — lets sessionLogs / APIs resolve cold rows. */
    archivedSessionId: v.string(),
    tableId: v.id("tables"),
    clubId: v.id("clubs"),
    customerId: v.optional(v.id("users")),
    guestName: v.optional(v.string()),
    guestAge: v.optional(v.number()),
    isGuest: v.boolean(),
    startTime: v.number(),
    endTime: v.optional(v.number()),
    billableMinutes: v.optional(v.number()),
    ratePerMin: v.number(),
    minBillMinutes: v.number(),
    currency: v.string(),
    snackOrders: v.array(snackOrder),
    billTotal: v.optional(v.number()),
    discount: v.optional(v.number()),
    paymentMethod: v.optional(paymentMethod),
    paymentStatus: paymentStatus,
    status: sessionStatus,
    cancellationReason: v.optional(v.string()),   // Mirrors sessions.cancellationReason
    timerAlertMinutes: v.optional(v.number()),
    timerAlertFiredAt: v.optional(v.number()),
    creditResolvedAt: v.optional(v.number()),
    creditResolvedMethod: v.optional(creditResolveMethod),
    staffAcknowledgedComplaint: v.optional(v.boolean()),
    acknowledgedByRoleId: v.optional(v.id("staffRoles")),
    acknowledgedAt: v.optional(v.number()),
    bookingId: v.optional(v.id("bookings")),
    discountAppliedByRoleId: v.optional(v.id("staffRoles")),
    discountAppliedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    // FIX #10: Monthly financial aggregate queries need to filter by club
    .index("by_club", ["clubId"])
    .index("by_archived_sessionId", ["archivedSessionId"]),

});